name: base
channels:
  - defaults
dependencies:
  - blas
  - numpy
  - numpy-base
  - pip=19.2.2
  - scipy=1.3.1
  - python=3.7
  - setuptools
  - six=1.12.0
  - wheel=0.33.4
  - flask=1.0.3
  - pip:
    - decorator==4.4.0
    - dlib==19.17.0
    - imageio==2.5.0
    - imutil==0.2.5
    - imutils==0.5.3
    - networkx==2.3
    - opencv-python~=4.2.0.34
    - pillow==6.1.0
    - pywavelets==1.0.3
    - scikit-image==0.15.0
    - azure-iot-device~=2.1.2
    - azure-storage-blob
    - setuptools
    - ptvsd==4.1.3
    - onnxruntime==0.5.0
    - requests
